In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import re

dir_path = r'train'
data_pattern = r'^.*_data\.csv$'
result_data = [f for f in os.listdir(dir_path) if re.match(data_pattern, f)]
events_pattern = r'^.*_events\.csv$'
result_events = [f for f in os.listdir(dir_path) if re.match(events_pattern, f)]

In [2]:
dir_path = r'train'
data_df_list = []
for file in result_data:
    df = pd.read_csv(os.path.join(dir_path, file))
    df.drop(['id'], axis=1, inplace=True) 
    data_df_list.append(df)

In [3]:
dir_path = r'train'
event_df_list = []
for file in result_events:
    df = pd.read_csv(os.path.join(dir_path, file))
    df.drop(['id'], axis=1, inplace=True) 
    event_df_list.append(df)

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [5]:
X = data_df_list[0]
y = event_df_list[0]
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size = .3, random_state = 1, stratify = y)

In [6]:
y_train

,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased
180835,0,0,0,0,0,0
75143,0,0,0,0,0,0
33325,0,0,0,0,0,0
239474,0,0,0,0,0,0
2187,0,0,0,0,0,0
...,...,...,...,...,...,...
205238,0,0,0,0,0,0
50033,0,0,0,0,0,0
137188,0,0,0,0,0,0
223316,0,0,0,0,0,0
131763,0,0,0,0,0,0

In [7]:
randomForestModel = RandomForestClassifier(n_estimators=100, criterion='gini')
randomForestModel.fit(X_train, y_train)
predicted = randomForestModel.predict(X_train)
#print(X)
#print(predicted)
#print(y_train)

print('訓練集: ',randomForestModel.score(X_train,y_train))
print('測試集: ',randomForestModel.score(X_test,y_test))

訓練集:  1.0
測試集:  0.9378914338707014

In [8]:
X2 = data_df_list[1]
y2 = event_df_list[1]

In [9]:
#predicted2 = randomForestModel.predict(X2)
print('測試集2: ',randomForestModel.score(X2,y2))

測試集2:  0.899328178242566

In [10]:
X3 = data_df_list[10]
y3 = event_df_list[10]
print('測試集2: ',randomForestModel.score(X3,y3))

測試集2:  0.8808578564855678

In [11]:
X4 = data_df_list[35]
y4 = event_df_list[35]
print('測試集2: ',randomForestModel.score(X4,y4))

測試集2:  0.8767735532910964

In [12]:
X5 = data_df_list[60]
y5 = event_df_list[60]
print('測試集2: ',randomForestModel.score(X5,y5))

測試集2:  0.8807994397295038

In [13]:
data_df = pd.concat(data_df_list)

In [14]:
data_df

,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,FC2,...,P7,P3,Pz,P4,P8,PO9,O1,Oz,O2,PO10
0,-304,-156,-411,-640,-505,-603,-451,104,-344,-784,...,-197,-597,-242,-472,-56,-338,-335,-518,-371,-177
1,-300,-151,-376,-670,-509,-622,-422,60,-374,-815,...,-203,-611,-224,-471,-53,-310,-326,-511,-396,-189
2,-286,-227,-400,-724,-525,-631,-469,70,-378,-811,...,-176,-608,-234,-475,-78,-282,-289,-505,-424,-193
3,-281,-272,-447,-702,-540,-640,-492,71,-386,-807,...,-154,-605,-246,-488,-73,-304,-337,-539,-412,-192
4,-294,-194,-432,-693,-503,-609,-500,109,-385,-797,...,-146,-602,-226,-448,-25,-342,-333,-549,-400,-157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127489,-62,45,134,-1254,-16,265,-126,64,-3,-211,...,-114,-77,99,-248,-38,-303,-27,-241,-901,-303
127490,-79,48,111,-1259,-27,278,-42,48,-20,-223,...,-74,-92,97,-258,-49,-337,-66,-248,-891,-319
127491,-87,26,120,-1250,-20,268,0,68,-18,-234,...,-65,-92,93,-270,-85,-387,-87,-253,-918,-386
127492,-35,90,182,-1279,-23,296,18,68,-12,-208,...,-40,-56,106,-234,-76,-397,-55,-213,-871,-403
127493,-43,127,192,-1273,-31,290,-45,39,-17,-210,...,-23,-44,123,-236,-58,-382,-51,-226,-893,-438

In [15]:
event_df = pd.concat(event_df_list)

In [16]:
event_df

,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased
0,0,0,0,0,0,0
1,0,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0
...,...,...,...,...,...,...
127489,0,0,0,0,0,0
127490,0,0,0,0,0,0
127491,0,0,0,0,0,0
127492,0,0,0,0,0,0
127493,0,0,0,0,0,0

In [17]:
X_train

,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,FC2,...,P7,P3,Pz,P4,P8,PO9,O1,Oz,O2,PO10
180835,-135,-414,-259,-343,-388,-231,-410,-515,-145,-351,...,-121,-131,-1,-207,-194,-337,-307,-677,-277,-412
75143,-22,-112,-381,-636,-430,-268,-402,-135,-335,-168,...,-429,-660,-313,-511,-382,-411,-372,-830,-605,-663
33325,-686,-212,-164,-534,-406,-175,-413,-75,-212,-451,...,-210,-522,-57,-116,78,-253,-278,-593,-357,-523
239474,1188,828,275,91,31,-178,-382,236,-169,-421,...,-452,-401,-228,-484,-357,-572,-541,-802,-553,-785
2187,-446,-165,-545,-605,-553,242,-96,74,-358,-718,...,-256,-257,2,-348,96,-330,-249,-480,-357,-136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205238,22,14,307,-242,-203,367,172,159,-90,-140,...,487,327,216,11,242,113,418,-343,63,77
50033,-359,-548,-236,-649,-462,-609,-586,-129,-328,-659,...,-351,-639,-512,-486,-265,-451,-439,-782,-580,-751
137188,17,-469,26,-422,-270,-99,-91,-218,-146,-339,...,-115,-282,-2,-129,65,-276,-193,-719,-248,-469
223316,37,149,204,-248,-357,-171,-236,-67,-188,-260,...,4,-184,-17,-310,2,-204,-261,-823,-442,-288
131763,181,39,-510,-342,-305,-249,-280,-122,-162,-366,...,-56,-130,-56,-156,-66,-143,-37,-381,-133,-545

In [18]:
y_train

,HandStart,FirstDigitTouch,BothStartLoadPhase,LiftOff,Replace,BothReleased
180835,0,0,0,0,0,0
75143,0,0,0,0,0,0
33325,0,0,0,0,0,0
239474,0,0,0,0,0,0
2187,0,0,0,0,0,0
...,...,...,...,...,...,...
205238,0,0,0,0,0,0
50033,0,0,0,0,0,0
137188,0,0,0,0,0,0
223316,0,0,0,0,0,0
131763,0,0,0,0,0,0